#!/usr/bin/env python3
"""PersonaX 本地服务接口：只暴露对话，不暴露发布动作。"""
from __future__ import annotations

import hmac
import json
import os
import threading
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Annotated, Any, Protocol

import yaml
from fastapi import Depends, FastAPI, HTTPException, Response, Security, status
from fastapi.openapi.docs import get_swagger_ui_html
from fastapi.openapi.utils import get_openapi
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse, StreamingResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel

from core.assistant import AssistantCheckpointStore, AssistantOrchestrator
from core.envfile import load_env_file
from core.harness import Harness, RuleConfig
from core.limits import SlidingWindowRateLimiter
from core.types import AssistantAPIRequest, AssistantRequest, AssistantResponse


ROOT = Path(__file__).resolve().parent
API_VERSION = "2.8.1"
_BEARER = HTTPBearer(auto_error=False)

_DOC_LANGUAGES: dict[str, dict[str, str]] = {
    "zh-CN": {
        "html_lang": "zh-CN",
        "page_title": "PersonaX 接口文档（简体中文）",
        "api_title": "PersonaX 助手 API",
        "summary": "本地 Agent 问答服务",
        "description": (
            "提供 JSON 完整回复与 SSE 流式回复。技术字段、路径和事件名保留英文，"
            "操作说明使用简体中文；接口层不提供真实发布能力。"
        ),
        "notice": "说明已汉化；Swagger UI 固有按钮保留英文，避免误译技术动作。",
    },
    "en": {
        "html_lang": "en",
        "page_title": "PersonaX API Documentation (English)",
        "api_title": "PersonaX Assistant API",
        "summary": "Local Agent assistant service",
        "description": (
            "Provides complete JSON replies and SSE streaming replies. "
            "The API layer does not expose real publishing actions."
        ),
        "notice": "English API reference. Technical fields, paths, and event names remain unchanged.",
    },
}

_OPERATION_DOCS: dict[tuple[str, str], dict[str, tuple[str, str]]] = {
    ("/healthz", "get"): {
        "zh-CN": ("存活检查", "检查 API 进程是否运行；不会加载大模型或知识库。"),
        "en": ("Liveness check", "Checks whether the API process is running without loading the model or knowledge base."),
    },
    ("/readyz", "get"): {
        "zh-CN": ("就绪检查", "初始化并检查助手服务是否可以接收请求。"),
        "en": ("Readiness check", "Initializes and checks whether the assistant service can accept requests."),
    },
    ("/v1/assistant/reply", "post"): {
        "zh-CN": ("获取完整回答", "提交一次 Agent 问答，返回完整 JSON 结果、引用来源和执行轨迹。"),
        "en": ("Get a complete reply", "Runs one Agent request and returns the complete JSON result, sources, and trace."),
    },
    ("/v1/assistant/stream", "post"): {
        "zh-CN": ("获取流式回答", "通过 SSE 返回 token、done 或 error 事件；事件名保持英文。"),
        "en": ("Stream a reply", "Streams token, done, or error events over SSE."),
    },
}

_REQUEST_FIELD_DOCS: dict[str, dict[str, str]] = {
    "question": {"zh-CN": "用户本轮问题。", "en": "The current user question."},
    "history": {"zh-CN": "最近对话历史，最多 20 条。", "en": "Recent conversation history, up to 20 messages."},
    "memories": {"zh-CN": "用户显式提供的长期记忆，最多 20 条。", "en": "Explicit user memories, up to 20 items."},
    "thread_id": {"zh-CN": "可选会话标识；省略时由服务端生成。", "en": "Optional thread identifier; generated by the server when omitted."},
    "use_knowledge": {"zh-CN": "是否允许检索本地知识库。", "en": "Whether local knowledge retrieval is enabled."},
    "max_steps": {"zh-CN": "Agent 最大执行步数。", "en": "Maximum number of Agent execution steps."},
    "max_estimated_tokens": {"zh-CN": "上下文估算 Token 上限。", "en": "Estimated context token budget."},
    "deadline_seconds": {"zh-CN": "单次请求截止时间（秒）。", "en": "Per-request deadline in seconds."},
}


class AssistantService(Protocol):
    """方便 API 测试替换真实模型，不扩散到核心编排层。"""

    def reply(self, request: AssistantRequest) -> AssistantResponse: ...

    def reply_stream(self, request: AssistantRequest) -> Any: ...


class HealthResponse(BaseModel):
    status: str
    version: str
    service: str = "personax-api"
    publish_api_exposed: bool = False
    api_token_required: bool = False


def _load_persona(path: Path | None = None) -> dict[str, Any]:
    target = path or ROOT / "config" / "persona.yaml"
    data = yaml.safe_load(target.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError("persona 配置必须是 YAML 对象")
    return data


def build_assistant_service() -> AssistantOrchestrator:
    """构建单进程共享服务；Harness 限流不会被每个请求重置。"""

    load_env_file(ROOT / ".env")
    persona = _load_persona()
    harness = Harness(RuleConfig(**(persona.get("harness", {}) or {})))
    checkpoint_path = Path(os.getenv(
        "PERSONAX_ASSISTANT_DB",
        str(ROOT / "logs" / "assistant_checkpoints.sqlite3"),
    ))
    return AssistantOrchestrator(
        persona,
        harness=harness,
        checkpoint_store=AssistantCheckpointStore(checkpoint_path),
        prompt_path=ROOT / "config" / "assistant_prompts.yaml",
    )


def _require_api_token(
    credentials: Annotated[
        HTTPAuthorizationCredentials | None,
        Security(_BEARER),
    ] = None,
) -> None:
    expected = os.getenv("PERSONAX_API_TOKEN", "").strip()
    if not expected:
        return
    supplied = credentials.credentials if credentials is not None else ""
    scheme = credentials.scheme if credentials is not None else ""
    if scheme.lower() != "bearer" or not hmac.compare_digest(supplied, expected):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={"code": "invalid_api_token", "message": "Bearer token 无效"},
            headers={"WWW-Authenticate": "Bearer"},
        )


def _sse(event: str, payload: Any) -> str:
    data = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return f"event: {event}\ndata: {data}\n\n"


def _positive_int_env(name: str, default: int, *, maximum: int = 10_000) -> int:
    try:
        value = int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default
    return max(1, min(value, maximum))


def _localize_openapi_schema(schema: dict[str, Any], language: str) -> None:
    """只翻译说明文字，路径、字段名、SSE 事件等技术契约保持英文。"""

    for (path, method), translations in _OPERATION_DOCS.items():
        operation = schema.get("paths", {}).get(path, {}).get(method)
        if not isinstance(operation, dict):
            continue
        summary, description = translations[language]
        operation["summary"] = summary
        operation["description"] = description
        operation["tags"] = ["系统 / System" if path in {"/healthz", "/readyz"} else "助手 / Assistant"]
        validation_error = operation.get("responses", {}).get("422")
        if isinstance(validation_error, dict):
            validation_error["description"] = (
                "请求参数校验失败" if language == "zh-CN" else "Request validation failed"
            )

    request_schema = (
        schema.get("components", {})
        .get("schemas", {})
        .get("AssistantAPIRequest", {})
    )
    properties = request_schema.get("properties", {})
    for field_name, translations in _REQUEST_FIELD_DOCS.items():
        field_schema = properties.get(field_name)
        if isinstance(field_schema, dict):
            field_schema["description"] = translations[language]

    request_schema["examples"] = [{
        "question": (
            "请介绍 PersonaX 的 RAG 流程"
            if language == "zh-CN"
            else "Explain the PersonaX RAG pipeline"
        ),
        "thread_id": "demo-1",
        "use_knowledge": True,
    }]


def _docs_navigation(language: str) -> str:
    copy = _DOC_LANGUAGES[language]
    return f"""
    <style>
      .personax-docs-nav {{
        position: sticky; top: 0; z-index: 10000; display: flex;
        align-items: center; gap: 14px; padding: 10px 24px;
        color: #f8fafc; background: #111827; font: 14px/1.5 system-ui, sans-serif;
        box-shadow: 0 1px 5px rgba(0, 0, 0, .25);
      }}
      .personax-docs-nav strong {{ margin-right: auto; }}
      .personax-docs-nav a {{ color: #bfdbfe; text-decoration: none; }}
      .personax-docs-nav a[aria-current="page"] {{ color: #fff; font-weight: 700; }}
      .personax-docs-note {{ color: #cbd5e1; }}
      @media (max-width: 760px) {{
        .personax-docs-nav {{ align-items: flex-start; flex-wrap: wrap; padding: 9px 12px; }}
        .personax-docs-nav strong {{ width: 100%; }}
        .personax-docs-note {{ width: 100%; }}
      }}
    </style>
    <nav class="personax-docs-nav" aria-label="API documentation language">
      <strong>PersonaX API</strong>
      <a href="/docs/zh-CN" {'aria-current="page"' if language == 'zh-CN' else ''}>简体中文</a>
      <a href="/docs/en" {'aria-current="page"' if language == 'en' else ''}>English</a>
      <a href="/openapi/{language}.json">OpenAPI JSON</a>
      <span class="personax-docs-note">{copy['notice']}</span>
    </nav>
    """


def create_app(
    service_factory: Callable[[], AssistantService] | None = None,
) -> FastAPI:
    """应用工厂；模型服务延迟初始化，健康检查不会触发模型加载。"""

    app = FastAPI(
        title="PersonaX Assistant API",
        version=API_VERSION,
        description="本地 Agent 问答 JSON/SSE 接口；不包含真实发布能力。",
        docs_url=None,
        redoc_url=None,
        openapi_url=None,
    )
    factory = service_factory or build_assistant_service
    service_lock = threading.Lock()
    request_limiter = SlidingWindowRateLimiter(
        _positive_int_env("PERSONAX_API_REQUESTS_PER_MINUTE", 60),
        window_seconds=60.0,
    )

    def get_service() -> AssistantService:
        current = getattr(app.state, "assistant_service", None)
        if current is not None:
            return current
        with service_lock:
            current = getattr(app.state, "assistant_service", None)
            if current is None:
                current = factory()
                app.state.assistant_service = current
        return current

    def enforce_request_rate() -> None:
        decision = request_limiter.check("api-global")
        if decision.allowed:
            return
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={"code": "api_rate_limited", "message": "请求过于频繁，请稍后重试"},
            headers={"Retry-After": str(request_limiter.retry_seconds(decision))},
        )

    localized_schemas: dict[str, dict[str, Any]] = {}

    def localized_schema(language: str) -> dict[str, Any]:
        cached = localized_schemas.get(language)
        if cached is not None:
            return cached
        copy = _DOC_LANGUAGES[language]
        schema = get_openapi(
            title=copy["api_title"],
            version=API_VERSION,
            summary=copy["summary"],
            description=copy["description"],
            routes=app.routes,
        )
        _localize_openapi_schema(schema, language)
        localized_schemas[language] = schema
        return schema

    def default_openapi() -> dict[str, Any]:
        return localized_schema("zh-CN")

    app.openapi = default_openapi  # type: ignore[method-assign]

    @app.get("/", include_in_schema=False)
    def root_docs() -> RedirectResponse:
        return RedirectResponse(url="/docs/zh-CN", status_code=status.HTTP_307_TEMPORARY_REDIRECT)

    @app.get("/docs", include_in_schema=False)
    def docs_default() -> RedirectResponse:
        return RedirectResponse(url="/docs/zh-CN", status_code=status.HTTP_307_TEMPORARY_REDIRECT)

    @app.get("/docs/{language}", include_in_schema=False)
    def docs_by_language(language: str) -> HTMLResponse:
        if language not in _DOC_LANGUAGES:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="不支持的文档语言")
        copy = _DOC_LANGUAGES[language]
        swagger_page = get_swagger_ui_html(
            openapi_url=f"/openapi/{language}.json",
            title=copy["page_title"],
            swagger_ui_parameters={
                "deepLinking": True,
                "displayRequestDuration": True,
                "persistAuthorization": True,
                "tryItOutEnabled": True,
            },
        )
        page = swagger_page.body.decode("utf-8")
        page = page.replace("<html>", f'<html lang="{copy["html_lang"]}">', 1)
        page = page.replace("<body>", f"<body>{_docs_navigation(language)}", 1)
        return HTMLResponse(
            page,
            headers={"Content-Language": language, "Cache-Control": "no-store"},
        )

    @app.get("/openapi/{language}.json", include_in_schema=False)
    def openapi_by_language(language: str) -> JSONResponse:
        if language not in _DOC_LANGUAGES:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="不支持的文档语言")
        return JSONResponse(
            localized_schema(language),
            headers={"Content-Language": language},
        )

    @app.get("/favicon.ico", include_in_schema=False)
    def favicon() -> Response:
        return Response(status_code=status.HTTP_204_NO_CONTENT)

    @app.get("/healthz", response_model=HealthResponse, tags=["system"])
    def health() -> HealthResponse:
        return HealthResponse(
            status="ok",
            version=API_VERSION,
            api_token_required=bool(os.getenv("PERSONAX_API_TOKEN", "").strip()),
        )

    @app.get("/readyz", response_model=HealthResponse, tags=["system"])
    def ready() -> HealthResponse:
        try:
            get_service()
        except Exception as exc:  # noqa: BLE001
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail={
                    "code": "service_not_ready",
                    "message": "助手配置初始化失败",
                    "error_type": type(exc).__name__,
                },
            ) from None
        return HealthResponse(
            status="ready",
            version=API_VERSION,
            api_token_required=bool(os.getenv("PERSONAX_API_TOKEN", "").strip()),
        )

    @app.post(
        "/v1/assistant/reply",
        response_model=AssistantResponse,
        tags=["assistant"],
        dependencies=[Depends(_require_api_token), Depends(enforce_request_rate)],
    )
    def reply(payload: AssistantAPIRequest, response: Response) -> AssistantResponse:
        request = payload.to_core_request()
        try:
            result = get_service().reply(request)
        except Exception as exc:  # noqa: BLE001
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail={
                    "code": "assistant_unavailable",
                    "message": "助手暂时不可用，请根据 trace_id 查看本地日志",
                    "trace_id": request.trace_id,
                    "error_type": type(exc).__name__,
                },
                headers={"X-Trace-ID": request.trace_id},
            ) from None
        response.headers["X-Trace-ID"] = result.trace_id
        return result

    @app.post(
        "/v1/assistant/stream",
        response_class=StreamingResponse,
        responses={200: {"content": {"text/event-stream": {}}}},
        tags=["assistant"],
        dependencies=[Depends(_require_api_token), Depends(enforce_request_rate)],
    )
    def stream(payload: AssistantAPIRequest) -> StreamingResponse:
        request = payload.to_core_request()

        def events() -> Iterator[str]:
            try:
                answer_stream = get_service().reply_stream(request)
                for chunk in answer_stream:
                    yield _sse("token", {"text": str(chunk)})
                completed = getattr(answer_stream, "response", None)
                if completed is None:
                    raise RuntimeError("回答流结束但缺少最终响应")
                yield _sse("done", completed.model_dump(mode="json"))
            except GeneratorExit:
                raise
            except Exception as exc:  # noqa: BLE001
                yield _sse("error", {
                    "code": "assistant_stream_failed",
                    "message": "流式回答中断，请重试",
                    "trace_id": request.trace_id,
                    "error_type": type(exc).__name__,
                })

        return StreamingResponse(
            events(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache, no-transform",
                "X-Accel-Buffering": "no",
                "X-Trace-ID": request.trace_id,
            },
        )

    return app


app = create_app()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("api:app", host="127.0.0.1", port=8000, workers=1)
